In [ ]:
# Install libraries if not already installed Note: it's generally preffered to install libraries from your local shell

# import sys

# !conda install --yes --prefix {sys.prefix} pandas
# !conda install --yes --prefix {sys.prefix} numpy
# !conda install --yes --prefix {sys.prefix} pandas

# !{sys.executable} -m pip install pandas
# !{sys.executable} -m pip install numpy
# !{sys.executable} -m pip install pandas

In [2]:
# Import libraries 
import pandas as pd
import numpy as np
import dtale as dt
import sweetviz as sv

In [3]:
# The path to the file you are trying to read

# df = pd.read_csv("path to your file")

# df = pd.read_excel("path to excel file")

df = pd.read_csv("C:\Coding\GitHub\Class-Datasets\diabetes_data.csv")

In [4]:
# advert_report = sv.analyze(df)
# advert_report.show_html('Advertising.html')

In [5]:
# dt.show(df)

In [6]:
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,30537.000000,3.053700e+04,30537.000000,30537.000000,30537.000000,30537.000000,30537.000000,30537.000000,30537.000000,30537.000000,30537.000000,30537.000000
mean,157015.239742,2.361568e+06,3.159511,3.710974,5.755641,0.261733,0.321836,0.223729,0.008878,0.002636,0.030325,6.434915
std,82402.900178,1.499345e+06,2.750271,5.265075,4.071725,0.229271,0.150153,0.284654,0.030091,0.013092,0.060750,1.940351
min,15020.000000,4.896200e+04,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,84971.000000,1.022362e+06,1.000000,1.000000,1.000000,0.076923,0.229008,0.000000,0.000000,0.000000,0.000000,5.000000
50%,157468.000000,2.145908e+06,1.000000,1.000000,7.000000,0.230769,0.328244,0.166667,0.000000,0.000000,0.000000,7.000000
75%,228301.000000,3.672708e+06,6.000000,4.000000,7.000000,0.384615,0.427481,0.333333,0.000000,0.000000,0.047619,8.000000
max,299996.000000,5.199508e+06,8.000000,28.000000,25.000000,1.000000,1.000000,1.000000,0.928571,1.000000,0.809524,15.000000